<?php


namespace Redrye\LaravelWebSocketsCrud\app\WebSockets\Messages;


use BeyondCode\LaravelWebSockets\Contracts\ChannelManager;
use BeyondCode\LaravelWebSockets\Contracts\PusherMessage;
use BeyondCode\LaravelWebSockets\Server\Messages\PusherChannelProtocolMessage;
use BeyondCode\LaravelWebSockets\Server\Messages\PusherClientMessage;
use BeyondCode\LaravelWebSockets\Server\Messages\PusherMessageFactory as DefaultPMF;
use Illuminate\Support\Str;
use \Log;
use Ratchet\ConnectionInterface;
use Ratchet\RFC6455\Messaging\MessageInterface;

class PusherMessageFactory extends DefaultPMF
{
	public static function createForMessage(MessageInterface $message, ConnectionInterface $connection, ChannelManager $channelManager): PusherMessage
	{
		$payload = json_decode($message->getPayload());
		if(Str::startsWith($payload->event, ['pusher:', 'client-'])) {
			return parent::createForMessage($message, $connection, $channelManager); // TODO: Change the autogenerated stub
		} else {
			return new PusherEventMessage($payload, $connection, $channelManager);
		}
	}
}
